services:
  app:
    build: .
    container_name: football-app
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=file:/app/data/football_app.db
      - NODE_ENV=production
      - PORT=4000
      - JWT_SECRET=0c6181bca1e065d914a891a0bc4cdfc282371750c05c155058b871d13bd1e1b3
      - AUTH_COOKIE_SECURE=false
    volumes:
      - ./data:/app/data
    restart: always
